name: bookly
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: ^3.8.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^17.0.0

  # Functional & State Management
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^9.1.0

  # Networking & API
  dio: ^5.9.0
  cached_network_image: ^3.4.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^6.0.0

  # Hive code generator
  hive_generator: ^2.0.1

  # Build runner (code generation)
  build_runner: ^2.4.13

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT-Sectra-Fine-Regular.ttf
